'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {MapPin,Share2,Download,Search,Plus,Minus,Maximize,ChevronLeft,Check,Loader2,Users,Trash2,Pencil,Lock,Copy,X} from 'lucide-react';
import ReedMark from '@/components/reed-mark';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {City,Experience,Kind,MapData,kinds,dateLabel,validateExperience,earliest,latest} from '@/lib/types';

const kindKeys=Object.keys(kinds) as Kind[];
const atlasColor='#b15d43';
const paperColor='#f4f1e9';
const inkColor='#30372e';
const fullView={x:0,y:0,w:1020,h:710};
function stampNumber(k:Kind){return String(kindKeys.indexOf(k)+1).padStart(2,'0');}
const blank={kind:'visit' as Kind,startDate:'',endDate:'',ongoing:false,note:''};
async function api(path:string,method='GET',body?:unknown):Promise<any>{const r=await fetch('/api/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});let b:any;try{b=await r.json();}catch{throw new Error('暂时无法连接，请稍后重试');}if(!r.ok)throw new Error(b.error||'操作未完成');return b;}
function short(name:string){return name.replace(/特别行政区|维吾尔自治区|壮族自治区|回族自治区|自治区|省|市$/g,'');}
export default function Footprints({user,initialOwner}:{user:{id:string;email:string;name:string};initialOwner:string}){
  const[map,setMap]=useState<MapData|null>(null),[records,setRecords]=useState<Experience[]>([]),[profile,setProfile]=useState({name:user.name||'我的足迹'}),[owner,setOwner]=useState(initialOwner||user.id),[ownerName,setOwnerName]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mapError,setMapError]=useState('');
  const[selected,setSelected]=useState<City|null>(null),[search,setSearch]=useState(''),[province,setProvince]=useState('all'),[filter,setFilter]=useState('all'),[year,setYear]=useState('all'),[panel,setPanel]=useState('regions'),[view,setView]=useState({x:0,y:0,w:1020,h:710}),[hover,setHover]=useState('');
  const[edit,setEdit]=useState(false),[draft,setDraft]=useState<typeof blank & {id?:string}>({...blank}),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[remove,setRemove]=useState<Experience|null>(null);
  const[shareOpen,setShareOpen]=useState(false),[shareEmail,setShareEmail]=useState(''),[outgoing,setOutgoing]=useState<{id:string;email:string}[]>([]),[incoming,setIncoming]=useState<{id:string;name:string}[]>([]),[shareError,setShareError]=useState(''),[shareBusy,setShareBusy]=useState(false),[shareLoaded,setShareLoaded]=useState(false);
  const[nameOpen,setNameOpen]=useState(false),[nameDraft,setNameDraft]=useState(''),[lastSaved,setLastSaved]=useState(''),[shareRemove,setShareRemove]=useState<{id:string;email:string}|null>(null);
  const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;view:typeof view;moved:boolean;cityId:string|null}|null>(null),loadSeq=useRef(0);
  const readOnly=owner!==user.id;
  async function loadMap(){setMapError('');try{const r=await fetch('/map.json');if(!r.ok)throw Error();setMap(await r.json());}catch{setMapError('地图未能加载，请重试');}}
  useEffect(()=>{void loadMap();void api('profile').then(setProfile).catch(()=>{});void loadShares();},[]);
  async function loadShares(){try{const b=await api('shares');setOutgoing(b.outgoing);setIncoming(b.incoming);setShareLoaded(true);setShareError('');}catch(e){setShareError((e as Error).message);}}
  async function loadRecords(target=owner){const seq=++loadSeq.current;setLoading(true);setError('');setRecords([]);try{const b=await api('experiences?owner='+encodeURIComponent(target));if(seq!==loadSeq.current)return;setRecords(b.records);setOwnerName(b.owner?.name||'');setLastSaved('已同步');}catch(e){if(seq===loadSeq.current)setError((e as Error).message);}finally{if(seq===loadSeq.current)setLoading(false);}}
  useEffect(()=>{setSelected(null);setEdit(false);void loadRecords(owner);},[owner]);
  const cityById=useMemo(()=>new Map(map?.cities.map(c=>[c.id,c])||[]),[map]);
  const visibleRecords=useMemo(()=>records.filter(e=>{if(year==='all')return true;const lo=year+'-01-01',hi=year+'-12-31';if(!e.startDate&&!e.endDate)return false;const start=e.startDate?earliest(e.startDate):e.endDate?earliest(e.endDate):lo;const end=e.ongoing?'2100-12-31':e.endDate?latest(e.endDate):e.startDate?latest(e.startDate):hi;return start<=hi&&end>=lo;}),[records,year]);
  const levels=useMemo(()=>{const m=new Map<string,Kind>();for(const r of visibleRecords){if(filter!=='all'&&r.kind!==filter)continue;const old=m.get(r.cityId);if(!old||kinds[r.kind].level>kinds[old].level)m.set(r.cityId,r.kind);}return m;},[visibleRecords,filter]);
  const scopeCities=useMemo(()=>map?.cities.filter(c=>province==='all'||c.province===province)||[],[map,province]);
  const scopeRecords=useMemo(()=>visibleRecords.filter(r=>province==='all'||cityById.get(r.cityId)?.province===province),[visibleRecords,cityById,province]);
  const stats=useMemo(()=>{const ids=new Set(scopeRecords.map(r=>r.cityId));return{cities:ids.size,provinces:new Set([...ids].map(id=>cityById.get(id)?.province).filter(Boolean)).size,...Object.fromEntries(kindKeys.map(k=>[k,new Set(scopeRecords.filter(r=>r.kind===k).map(r=>r.cityId)).size]))} as {cities:number;provinces:number}&Record<Kind,number>;},[scopeRecords,cityById]);
  const activeCount=filter==='all'?stats.cities:stats[filter as Kind];
  const scopeName=province==='all'?'全国':map?.provinces.find(p=>p.id===province)?.name||'当前地区';
  const coverage=scopeCities.length?Math.round(activeCount/scopeCities.length*1000)/10:0;
  const regionProgress=useMemo(()=>map?.provinces.map(p=>{const cs=map.cities.filter(c=>c.province===p.id);return{...p,total:cs.length,visited:cs.filter(c=>levels.has(c.id)).length,matches:(p.name+cs.map(c=>c.name).join(' ')).replace(/台/g,'臺').includes(search.trim().replace(/台/g,'臺'))};}).filter(p=>p.matches)||[],[map,levels,search]);
  const years=useMemo(()=>{const s=new Set<string>();records.forEach(r=>{if(r.startDate)s.add(r.startDate.slice(0,4));if(r.endDate)s.add(r.endDate.slice(0,4));if(r.startDate&&(r.endDate||r.ongoing)){for(let y=Number(r.startDate.slice(0,4));y<=Number((r.endDate||String(new Date().getFullYear())).slice(0,4));y++)s.add(String(y));}});return[...s].sort().reverse();},[records]);
  const cities=useMemo(()=>{if(!map)return[];const q=search.trim().replace(/台/g,'臺');return map.cities.filter(c=>(province==='all'||c.province===province)&&(!q||(c.name+map.provinces.find(p=>p.id===c.province)?.name).replace(/台/g,'臺').includes(q))&&(filter==='all'||levels.has(c.id))).sort((a,b)=>(levels.has(b.id)?1:0)-(levels.has(a.id)?1:0)||a.name.localeCompare(b.name,'zh-CN'));},[map,search,province,filter,levels]);
  const selectedRecords=records.filter(e=>e.cityId===selected?.id).sort((a,b)=>b.startDate.localeCompare(a.startDate)||b.updatedAt-a.updatedAt);
  const timeline=visibleRecords.filter(e=>filter==='all'||e.kind===filter).filter(e=>province==='all'||cityById.get(e.cityId)?.province===province).sort((a,b)=>b.startDate.localeCompare(a.startDate)||b.updatedAt-a.updatedAt);
  const timelineQuery=search.trim().replace(/台/g,'臺');
  const matchingTimeline=timeline.filter(e=>{const c=cityById.get(e.cityId);return !timelineQuery||(c?.name+' '+(map?.provinces.find(p=>p.id===c?.province)?.name||'')).replace(/台/g,'臺').includes(timelineQuery);});
  function focusCity(c:City,zoom=true){setSelected(c);setEdit(false);setFormError('');if(zoom){const b=c.bounds,w=Math.max(160,(b[2]-b[0])*2.5),h=w*710/1020;setView({x:c.center[0]-w/2,y:c.center[1]-h/2,w,h});}}
  function provinceView(id:string){if(id==='all'||!map)return fullView;const cs=map.cities.filter(c=>c.province===id);if(!cs.length)return fullView;const x0=Math.min(...cs.map(c=>c.bounds[0])),x1=Math.max(...cs.map(c=>c.bounds[2])),y0=Math.min(...cs.map(c=>c.bounds[1])),y1=Math.max(...cs.map(c=>c.bounds[3]));const w=Math.max(x1-x0,(y1-y0)*1020/710,100)*1.15;return{x:(x0+x1-w)/2,y:(y0+y1-w*710/1020)/2,w,h:w*710/1020};}
  function selectProvince(id:string){setProvince(id);setSelected(null);setEdit(false);setView(provinceView(id));}
  function zoom(factor:number){setView(v=>{const w=Math.min(1300,Math.max(100,v.w*factor));return{x:v.x+(v.w-w)/2,y:v.y+(v.h-w*710/1020)/2,w,h:w*710/1020};});}
  function startEdit(e?:Experience){setDraft(e?{...e}:{...blank});setEdit(true);setFormError('');}
  async function saveDraft(){if(!selected||readOnly||saving)return;setFormError('');const body={...draft,cityId:selected.id};try{validateExperience(body,new Set(cityById.keys()));}catch(e){setFormError((e as Error).message);return;}setSaving(true);try{const r=await api('experiences','POST',body);setRecords(old=>[r,...old.filter(e=>e.id!==r.id)]);setEdit(false);setLastSaved('刚刚保存');toast.success('已保存这段经历');}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}
  async function deleteRecord(){if(!remove)return;setSaving(true);try{await api('experiences','DELETE',{id:remove.id});setRecords(old=>old.filter(r=>r.id!==remove.id));setRemove(null);setLastSaved('刚刚保存');toast.success('记录已删除');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
  async function grant(){setShareError('');setShareBusy(true);try{await api('shares','POST',{email:shareEmail});setShareEmail('');await loadShares();toast.success('已授权查看你的地图');}catch(e){setShareError((e as Error).message);}finally{setShareBusy(false);}}
  async function revoke(){if(!shareRemove)return;setShareBusy(true);try{await api('shares','DELETE',{id:shareRemove.id});setShareRemove(null);await loadShares();toast.success('已收回查看权限');}catch(e){toast.error((e as Error).message);}finally{setShareBusy(false);}}
  async function copyLink(){try{await navigator.clipboard.writeText(location.origin+'/?owner='+encodeURIComponent(user.id));toast.success('地图链接已复制');}catch{toast.error('复制失败，请手动复制下方链接');}}
  function backup(){const blob=new Blob([JSON.stringify({version:1,name:readOnly?ownerName:profile.name,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'});downloadBlob(blob,'tabisuru-ashi-'+new Date().toISOString().slice(0,10)+'.json');}
  function downloadBlob(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  async function exportMap(){
    if(!svg.current||!map)return;
    let url='';
    try{
      const clone=svg.current.cloneNode(true) as SVGSVGElement,box=provinceView(province),exportScale=1020/box.w;
      clone.setAttribute('viewBox',`${box.x} ${box.y} ${box.w} ${box.h}`);clone.setAttribute('width','1900');clone.setAttribute('height','1323');
      clone.querySelectorAll('.province-label,.city-label').forEach(e=>e.remove());
      clone.querySelectorAll('[data-city]').forEach(e=>{e.setAttribute('stroke','#aaa797');e.setAttribute('stroke-width','0.55');});
      const labels=province==='all'?map.provinces.filter(p=>!['810000','820000'].includes(p.id)):scopeCities;
      for(const item of labels){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',String(item.center[0]));t.setAttribute('y',String(item.center[1]));t.setAttribute('text-anchor','middle');t.setAttribute('fill',inkColor);t.setAttribute('font-size',String(12/exportScale));t.setAttribute('font-family','sans-serif');t.textContent=short(item.name);clone.appendChild(t);}
      const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'});url=URL.createObjectURL(blob);const img=new Image();img.src=url;await img.decode();
      const canvas=document.createElement('canvas');canvas.width=2040;canvas.height=1900;const ctx=canvas.getContext('2d')!;ctx.fillStyle=paperColor;ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.fillStyle=inkColor;ctx.font='36px Georgia, serif';ctx.fillText('tabisuru-ashi',70,95);ctx.font='22px monospace';ctx.fillText('A PERSONAL ATLAS / PLACES & DAYS',70,137);
      const title=(readOnly?ownerName:profile.name)||'我的地图';let fontSize=64;while(fontSize>28){ctx.font=fontSize+'px serif';if(ctx.measureText(title).width<1870)break;fontSize-=2;}ctx.fillText(title,70,235,1870);
      ctx.font='26px sans-serif';ctx.fillText(scopeName+' / '+(year==='all'?'全部时间':year+' 年')+' / '+(filter==='all'?'全部经历':kinds[filter as Kind].label)+' · '+activeCount+' / '+scopeCities.length+' 个城市 · '+coverage+'%',70,294);
      ctx.strokeStyle='#bbb6a8';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(70,330);ctx.lineTo(1970,330);ctx.stroke();ctx.drawImage(img,70,345);
      ctx.beginPath();ctx.moveTo(70,1690);ctx.lineTo(1970,1690);ctx.stroke();
      kindKeys.forEach((k,i)=>{const x=70+i*430;ctx.strokeStyle=kinds[k].color;ctx.strokeRect(x,1730,330,68);ctx.fillStyle=kinds[k].color;ctx.font='24px monospace';ctx.fillText(stampNumber(k),x+17,1774);ctx.font='28px sans-serif';ctx.fillText(kinds[k].label+' / '+stats[k]+' 城市',x+72,1774);});
      ctx.fillStyle='#66695e';ctx.font='21px sans-serif';ctx.fillText('城市记录示意图 · 四类经历分别统计',70,1853);ctx.font='20px monospace';ctx.textAlign='right';ctx.fillText(new Date().toISOString().slice(0,10)+' / tabisuru-ashi',1970,1853);
      canvas.toBlob(b=>{if(b)downloadBlob(b,'tabisuru-ashi-atlas.png');else toast.error('图片导出失败');});
    }catch{toast.error('图片导出失败，请稍后重试');}finally{if(url)URL.revokeObjectURL(url);}
  }
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(t:any)=>{try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};
    register({name:'read_city_footprints',description:'Read the currently displayed city experiences.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({owner:readOnly?ownerName:profile.name,readOnly,records})});
    register({name:'start_city_experience',description:'Select a city and open the experience editor. Does not save a record.',inputSchema:{type:'object',properties:{cityId:{type:'string'}},required:['cityId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(readOnly)throw Error('Shared maps are read-only');const c=cityById.get(input?.cityId);if(!c)throw Error('Unknown city');focusCity(c);setDraft({...blank});setEdit(true);return{cityId:c.id,cityName:c.name,status:'editor_open'};}});return()=>life.abort();
  },[records,readOnly,map,profile.name,ownerName]);
  const scale=1020/view.w;
  const currentName=readOnly?ownerName:profile.name;
  return <div className="app">
    <Toaster position="bottom-center"/>
    <header className="topbar">
      <a className="brand" href="/" aria-label="tabisuru-ashi 首页"><ReedMark className="brand-reed"/><span>tabisuru-ashi</span></a>
      <nav aria-label="主导航"><button className={!readOnly?'nav active':'nav'} onClick={()=>{setOwner(user.id);setYear('all');}}>我的地图</button><button className="nav" onClick={()=>{setShareOpen(true);void loadShares();}}>朋友的地图</button></nav>
      <div className="top-actions"><span className="save-state"><i className={error?'sync-error':''}/>{loading?'正在同步':error?'尚未同步':lastSaved}</span><button className="button header-share" onClick={()=>{setShareOpen(true);void loadShares();}}><Share2 size={15}/>分享</button><button className="button subtle logout" onClick={async()=>{try{await api('auth/logout','POST',{});location.assign('/login');}catch(e){toast.error((e as Error).message);}}}>退出</button></div>
    </header>
    <main className="atlas-main">
      <section className="intro">
        <div className="intro-title"><div className="eyebrow">A PERSONAL ATLAS <span>/</span> PLACES & DAYS</div><div className="title-row"><h1>{currentName||(readOnly?'朋友的地图':'我的地图')}</h1>{readOnly?<span className="readonly">只读</span>:<button className="icon-button name-btn" aria-label="修改地图名称" onClick={()=>{setNameDraft(profile.name);setNameOpen(true);}}><Pencil size={15}/></button>}</div><p>经过的地方，停留的日子。</p></div>
        <div className="coverage"><span>{scopeName} · {filter==='all'?'有记录的城市':kinds[filter as Kind].label+' · 城市'}</span><div><strong>{loading?'—':activeCount}</strong><span>/ {map?scopeCities.length:'—'} <small>城市</small></span></div><p>{coverage}% 覆盖度 {province==='all'&&<span>· {stats.provinces} 个省级地区</span>}</p></div>
      </section>
      <section className="record-index" aria-label="按经历查看地图"><span className="index-label">经历索引</span><button className={filter==='all'?'index-kind active':'index-kind'} aria-pressed={filter==='all'} onClick={()=>setFilter('all')}><span>全部</span><b>{loading?'—':stats.cities}</b></button>{kindKeys.map(k=><button key={k} className={'index-kind '+(filter===k?'active':'')} aria-pressed={filter===k} style={{'--kind-color':kinds[k].color} as React.CSSProperties} onClick={()=>setFilter(filter===k?'all':k)}><span className="kind-code">{stampNumber(k)}</span><span>{kinds[k].label}</span><b>{loading?'—':stats[k]}</b></button>)}<span className="index-note">同一城市可有多种经历</span></section>
      {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void loadRecords()}>重新加载</button>{readOnly&&<button onClick={()=>setOwner(user.id)}>回到我的地图</button>}</div>}
      <div className="workspace">
        <section className="map-card" aria-label="地图集">
          <div className="map-toolbar"><div className="map-title"><span className="folio">01</span><strong>{province==='all'?'中国 · 城市地图':scopeName+' · 城市地图'}</strong></div><div className="map-tools"><Select value={year} onValueChange={setYear}><SelectTrigger aria-label="按年份查看" className="year-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部时间</SelectItem>{years.map(y=><SelectItem key={y} value={y}>{y} 年</SelectItem>)}</SelectContent></Select><button className="button subtle" onClick={()=>void exportMap()} disabled={!map||loading||!!error}><Download size={15}/><span>保存图片</span></button></div></div>
          <div className="map-surface">{map?<svg ref={svg} xmlns="http://www.w3.org/2000/svg" viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} aria-label="中国城市足迹地图" tabIndex={0} onKeyDown={e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(.72);}else if(e.key==='-'){e.preventDefault();zoom(1.38);}else if(e.key==='0'){e.preventDefault();selectProvince('all');}}} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,view:{...view},moved:false,cityId:(e.target as Element).getAttribute('data-city')};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const d=drag.current,rect=e.currentTarget.getBoundingClientRect(),dx=(e.clientX-d.x)*d.view.w/rect.width,dy=(e.clientY-d.y)*d.view.h/rect.height;if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>6)d.moved=true;if(d.moved)setView({...d.view,x:d.view.x-dx,y:d.view.y-dy});}} onPointerUp={e=>{const moved=drag.current?.moved,id=drag.current?.cityId;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!moved&&id){const c=cityById.get(id);if(c)focusCity(c,false);}}} onPointerCancel={()=>{drag.current=null;}}>
            <rect x="-10000" y="-10000" width="20000" height="20000" fill={paperColor}/>
            {map.cities.map(c=><path key={c.id} data-city={c.id} d={c.path} fill={levels.has(c.id)?filter==='all'?atlasColor:kinds[filter as Kind].color:'#fffdf8'} stroke={selected?.id===c.id?inkColor:'#aaa797'} strokeWidth={selected?.id===c.id?2.3:.55} opacity={province!=='all'&&c.province!==province?0.48:1} vectorEffect="non-scaling-stroke" fillRule="evenodd" className="city-path" onMouseEnter={()=>setHover(c.name)} onMouseLeave={()=>setHover('')} role="button" aria-label={c.name+(levels.has(c.id)?'，有记录':'，未记录')} tabIndex={selected?.id===c.id?0:-1} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focusCity(c,false);}}}><title>{c.name}{levels.has(c.id)?' · 有记录':''}</title></path>)}
            {map.provinces.map(p=><path key={'p'+p.id} d={p.path} fill="none" stroke="#777d6b" strokeWidth=".9" vectorEffect="non-scaling-stroke" pointerEvents="none"/>)}
            <g pointerEvents="none"><rect x="838" y="504" width="150" height="175" fill={paperColor} stroke="#aaa797" strokeWidth=".7"/>{map.inset?.map((p,i)=><path key={'inset'+i} d={p.path} fill={p.id==='460000'&&levels.has('460300')?filter==='all'?atlasColor:kinds[filter as Kind].color:'#fffdf8'} stroke="#aaa797" strokeWidth=".6"/>)}<text x="851" y="525" fill="#727767" fontSize="10" fontFamily="sans-serif">南海诸岛</text></g>
            {scale<2.3&&map.provinces.filter(p=>!['810000','820000'].includes(p.id)).map(p=><text key={'label'+p.id} className="province-label" x={p.center[0]} y={p.center[1]} textAnchor="middle" fill={inkColor} fontSize={12/scale} fontFamily="sans-serif" pointerEvents="none">{short(p.name)}</text>)}
            {scale>=2.3&&map.cities.filter(c=>c.center[0]>view.x&&c.center[0]<view.x+view.w&&c.center[1]>view.y&&c.center[1]<view.y+view.h).map(c=><text key={'label'+c.id} className="city-label" x={c.center[0]} y={c.center[1]} textAnchor="middle" fill={inkColor} fontSize={12/scale} fontFamily="sans-serif" pointerEvents="none">{short(c.name)}</text>)}
          </svg>:<div className="map-loading">{mapError?<><span>{mapError}</span><button className="button" onClick={()=>void loadMap()}>重试</button></>:<><Loader2 className="spin" size={22}/>正在载入城市地图</>}</div>}</div>
          <div className="map-controls"><span className="map-hint">{hover||'选择一个城市，打开它的档案'}</span><div className="zoom-controls"><button aria-label="放大地图" onClick={()=>zoom(.72)}><Plus size={17}/></button><button aria-label="缩小地图" onClick={()=>zoom(1.38)}><Minus size={17}/></button><button aria-label="显示全国" onClick={()=>selectProvince('all')}><Maximize size={16}/></button></div></div>
          <div className="map-footer"><div className="legend"><span><i style={{background:filter==='all'?atlasColor:kinds[filter as Kind].color}}/>{filter==='all'?'有记录':kinds[filter as Kind].label}</span><span><i/>未记录</span></div><span className="map-instruction">拖动地图 · + / − 缩放</span><span className="north">N ↑</span></div>
          <details className="map-note"><summary>地图范围与来源</summary><p>地级行政区、直辖市与省直辖县级单位；港澳按地区、台湾按县市记录。边界来源：<a href="https://datav.aliyun.com/portal/school/atlas/area_selector" target="_blank" rel="noreferrer">DataV.GeoAtlas</a> / <a href="https://github.com/titaneric/Taiwan-GeoJSON" target="_blank" rel="noreferrer">台湾县市图资</a> · 旅行记录示意地图</p></details>
        </section>
        <aside className="side-card" aria-label={selected?'城市档案':'地图目录'}>{selected?<>
          <div className="detail-header"><button className="back" onClick={()=>{setSelected(null);setEdit(false);}}><ChevronLeft size={15}/>返回目录</button><div className="archive-heading"><span className="eyebrow">CITY / {selected.id}</span><span className="secondary">{map?.provinces.find(p=>p.id===selected.province)?.name}</span></div><h2>{selected.name}</h2><p>{selectedRecords.length} 段经历 · 全部时间{readOnly?' · 只读':''}</p><div className="city-stamps" aria-label="这个城市的经历类型">{kindKeys.map(k=><span key={k} className={'city-stamp '+(selectedRecords.some(r=>r.kind===k)?'has-record':'')} style={{'--kind-color':kinds[k].color} as React.CSSProperties}>{kinds[k].label}<small>{selectedRecords.filter(r=>r.kind===k).length||'—'}</small></span>)}</div></div>
          <div className="detail-body">{edit?<form onSubmit={e=>{e.preventDefault();void saveDraft();}}><h3>{draft.id?'编辑经历':'添一段经历'}</h3><div className="kind-choices">{kindKeys.map(k=><button key={k} type="button" aria-pressed={draft.kind===k} className={draft.kind===k?'chosen':''} style={{'--kind-color':kinds[k].color} as React.CSSProperties} onClick={()=>setDraft({...draft,kind:k})}><span>{stampNumber(k)}</span>{kinds[k].label}{draft.kind===k&&<Check size={14}/>}</button>)}</div><label className="field">开始时间<input placeholder="例如 2026-10-01" inputMode="text" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label><label className="field">结束时间 <span>可选</span><input placeholder="同一天可留空" value={draft.endDate} disabled={draft.ongoing} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></label><label className="check-field"><Checkbox checked={draft.ongoing} onCheckedChange={v=>setDraft({...draft,ongoing:!!v,endDate:v?'':draft.endDate})}/>持续至今</label><p className="field-hint">支持年份、年月或完整日期。<br/>不记得时间，也可以留空。</p><label className="field">备注 <span>可选</span><textarea placeholder="在这里留下一点记忆。" rows={3} maxLength={1000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="button" type="button" disabled={saving} onClick={()=>setEdit(false)}>取消</button><button className="button primary" disabled={saving} type="submit">{saving&&<Loader2 size={15} className="spin"/>}保存经历</button></div></form>:<>
            {!readOnly&&<button className="button add-record" disabled={loading||!!error} onClick={()=>startEdit()}><Plus size={15}/>添加经历</button>}
            {selectedRecords.length===0?<div className="empty-state"><span className="empty-number">—</span><h3>这一页，尚待书写。</h3><p>{readOnly?'这位朋友还没有记录这个城市。':'记录经过、游玩、住宿或居住，时间可以精确到某一天。'}</p></div>:<div className="experience-list">{selectedRecords.map(e=><article className="experience" key={e.id}><div className="experience-title"><span className="entry-stamp" style={{'--kind-color':kinds[e.kind].color} as React.CSSProperties}><b>{stampNumber(e.kind)}</b>{kinds[e.kind].label}</span>{!readOnly&&<div className="entry-actions"><button aria-label="编辑这条记录" onClick={()=>startEdit(e)}><Pencil size={14}/></button><button aria-label="删除这条记录" onClick={()=>setRemove(e)}><Trash2 size={14}/></button></div>}</div><time>{dateLabel(e)}</time>{e.note&&<p>{e.note}</p>}</article>)}</div>}
            <div className="detail-foot">{readOnly?'朋友的档案 · 仅可查看':'账号保存 · 仅向指定朋友开放'}</div>
          </>}</div>
        </>:<>
          <div className="side-header"><div className="directory-title"><span className="eyebrow">INDEX / 目录</span><span className="folio">02</span></div><Tabs value={panel} onValueChange={setPanel}><TabsList variant="line" className="panel-tabs"><TabsTrigger value="regions">地区</TabsTrigger><TabsTrigger value="cities">城市</TabsTrigger><TabsTrigger value="timeline">时间</TabsTrigger></TabsList></Tabs><div className="search-field"><Search size={15}/><input aria-label="搜索城市" placeholder="搜索省份或城市" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="清除搜索" onClick={()=>setSearch('')}><X size={14}/></button>}</div>{panel!=='regions'&&<Select value={province} onValueChange={selectProvince}><SelectTrigger className="province-select" aria-label="选择省级地区"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全国 · 全部地区</SelectItem>{map?.provinces.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select>}</div>
          <div className="list-label"><span>{panel==='regions'?'省内城市覆盖度':panel==='cities'?'城市目录':'按开始时间排序'}</span><span>{panel==='regions'?regionProgress.length+' 地区':panel==='cities'?cities.length+' 城市':timeline.length+' 段'}</span></div>
          <div className="city-list">{loading||!map?<div className="empty-state"><Loader2 className="spin"/>正在读取地图档案</div>:panel==='regions'?regionProgress.length?regionProgress.map(p=><button className="region-row" key={p.id} onClick={()=>{selectProvince(p.id);setPanel('cities');}}><span className="region-name">{p.name}<span className="region-count">{p.visited}<small> / {p.total}</small></span></span><span className="region-line"><i style={{width:(p.total?p.visited/p.total*100:0)+'%'}}/></span></button>):<div className="empty-state"><h3>没有找到地区</h3><p>试试另一个名称。</p></div>:panel==='cities'?cities.length?cities.map(c=><button className="city-row" key={c.id} onClick={()=>focusCity(c)}><span>{c.name}<small>{map.provinces.find(p=>p.id===c.province)?.name}</small></span><span className="row-stamps" aria-label={kindKeys.filter(k=>visibleRecords.some(r=>r.cityId===c.id&&r.kind===k)).map(k=>kinds[k].label).join('、')||'未记录'}>{kindKeys.filter(k=>visibleRecords.some(r=>r.cityId===c.id&&r.kind===k)).map(k=><i key={k} style={{'--kind-color':kinds[k].color} as React.CSSProperties}>{kinds[k].label}</i>)}{!visibleRecords.some(r=>r.cityId===c.id)&&<small>未记录</small>}</span></button>):<div className="empty-state"><h3>没有找到城市</h3><p>试试调整名称或地区筛选。</p></div>:matchingTimeline.length?matchingTimeline.map(e=><button className="timeline-row" key={e.id} onClick={()=>{const c=cityById.get(e.cityId);if(c)focusCity(c);}}><span><strong>{cityById.get(e.cityId)?.name}</strong><small>{dateLabel(e)}</small></span><span className="mini-stamp" style={{'--kind-color':kinds[e.kind].color} as React.CSSProperties}>{kinds[e.kind].label}</span></button>):<div className="empty-state"><span className="empty-number">—</span><h3>这里，还没有记录。</h3><p>选择一个城市，添一段经历。</p></div>}</div>
          <div className="sidebar-bottom">{readOnly?'朋友的档案 · 仅可查看':'城市去重统计 · 经历分别保留'}</div>
        </>}</aside>
      </div>
      <footer className="page-footer"><span><ReedMark/>tabisuru-ashi <span className="footer-sep">/</span> PLACES & DAYS</span><button onClick={backup} disabled={loading||!!error}><Download size={14}/>备份记录 JSON</button></footer>
    </main>
    <Dialog open={shareOpen} onOpenChange={setShareOpen}><DialogContent className="share-dialog"><DialogTitle>和朋友交换足迹</DialogTitle><DialogDescription>每人拥有独立地图。只有你指定的朋友，才能看到你的记录。</DialogDescription><div className="share-section"><h3><Users size={17}/>朋友分享给我的地图</h3>{incoming.length?<div className="friend-list">{incoming.map(f=><button key={f.id} onClick={()=>{setOwner(f.id);setYear('all');setShareOpen(false);}}><span className="friend-avatar"><ReedMark/></span><span>{f.name}<small>只读查看</small></span><MapPin size={17}/></button>)}</div>:<p className="muted-copy">朋友向你的邮箱授权后，地图会出现在这里。</p>}</div><div className="share-section"><h3><Share2 size={17}/>谁可以看我的地图</h3><form className="share-form" onSubmit={e=>{e.preventDefault();void grant();}}><input aria-label="朋友的邮箱" type="email" placeholder="朋友的网站登录邮箱" required value={shareEmail} onChange={e=>setShareEmail(e.target.value)}/><button className="button primary" disabled={shareBusy}>{shareBusy?'处理中':'授权'}</button></form>{shareError&&<p className="form-error" role="alert">{shareError}</p>}{!shareLoaded&&<button className="button" onClick={()=>void loadShares()}>重新读取分享名单</button>}<div className="share-list">{outgoing.map(s=><div key={s.id}><span>{s.email}</span><button disabled={shareBusy} onClick={()=>setShareRemove(s)}>收回权限</button></div>)}</div><div className="share-link"><input aria-label="我的地图分享链接" readOnly value={typeof location!=='undefined'?location.origin+'/?owner='+encodeURIComponent(user.id):''}/><button className="button" onClick={()=>void copyLink()}><Copy size={15}/>复制</button></div><div className="share-notice"><Lock size={16}/><p>首次使用时，朋友需先由网站主人创建账号并开放网站访问。这里的授权只决定谁能查看你的地图，不发送邮件。获邀朋友也能记录自己的足迹；收回授权后将无法再读取你的地图。</p></div></div></DialogContent></Dialog>
    <Dialog open={nameOpen} onOpenChange={setNameOpen}><DialogContent><DialogTitle>给你的地图起个名字</DialogTitle><DialogDescription>这个名字也会显示在分享给朋友的地图上。</DialogDescription><form onSubmit={async e=>{e.preventDefault();setSaving(true);try{await api('profile','PUT',{name:nameDraft});setProfile({name:nameDraft.trim()});setNameOpen(false);toast.success('地图名称已保存');}catch(err){toast.error((err as Error).message);}finally{setSaving(false);}}}><label className="field">地图名称<input maxLength={40} required value={nameDraft} onChange={e=>setNameDraft(e.target.value)}/></label><button className="button primary" disabled={saving}>保存名称</button></form></DialogContent></Dialog>
    <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!saving)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这段经历？</AlertDialogTitle><AlertDialogDescription>{remove?dateLabel(remove):''} · 删除后无法恢复，其他记录会保留。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>取消</AlertDialogCancel><AlertDialogAction className="danger-button" disabled={saving} onClick={e=>{e.preventDefault();void deleteRecord();}}>{saving?'正在删除':'删除记录'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!shareRemove} onOpenChange={v=>{if(!v&&!shareBusy)setShareRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>收回查看权限？</AlertDialogTitle><AlertDialogDescription>{shareRemove?.email} 将无法再查看你的足迹；对方自己的地图会保留。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={shareBusy}>取消</AlertDialogCancel><AlertDialogAction disabled={shareBusy} onClick={e=>{e.preventDefault();void revoke();}}>收回权限</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
