export type Kind='visit'|'stay'|'live';
export type Experience={id:string;cityId:string;kind:Kind;startDate:string;endDate:string;ongoing:boolean;note:string;updatedAt:number};
export type City={id:string;name:string;province:string;path:string;center:number[];bounds:number[]};
export type Province={id:string;name:string;path:string;center:number[]};
export type MapData={cities:City[];provinces:Province[];inset:{path:string;id:string;name:string}[];width:number;height:number;source:string;retrieved:string};
export const kinds={visit:{label:'游玩',color:'#38a99e',level:3},stay:{label:'住宿',color:'#f1b34c',level:4},live:{label:'居住',color:'#e77767',level:5}};
export function validPartialDate(v:unknown):v is string{if(typeof v!=='string')return false;if(v==='')return true;if(!/^\d{4}(-\d{2})?(-\d{2})?$/.test(v))return false;const [y,m,d]=v.split('-').map(Number);return y>=1900&&y<=2100&&(m===undefined||(m>=1&&m<=12))&&(d===undefined||(d>=1&&d<=new Date(Date.UTC(y,m,0)).getUTCDate()));}
export function earliest(v:string){return v.length===4?v+'-01-01':v.length===7?v+'-01':v;}
export function latest(v:string){if(v.length===4)return v+'-12-31';if(v.length===7){const[y,m]=v.split('-').map(Number);return v+'-'+new Date(Date.UTC(y,m,0)).getUTCDate();}return v;}
export function validateExperience(b:Record<string,unknown>,ids:Set<string>){if(typeof b.cityId!=='string'||!ids.has(b.cityId))throw new Error('请选择有效城市');if(!['visit','stay','live'].includes(String(b.kind)))throw new Error('请选择经历类型');if(!validPartialDate(b.startDate)||!validPartialDate(b.endDate))throw new Error('时间格式应为 YYYY、YYYY-MM 或 YYYY-MM-DD');if(typeof b.ongoing!=='boolean'||typeof b.note!=='string'||b.note.length>1000)throw new Error('备注最多 1000 字');if(b.ongoing&&b.endDate)throw new Error('持续至今时不应填写结束时间');if(b.startDate&&b.endDate&&earliest(b.startDate)>latest(b.endDate))throw new Error('结束时间不能早于开始时间');return {cityId:b.cityId,kind:b.kind as Kind,startDate:b.startDate,endDate:b.endDate,ongoing:b.ongoing,note:b.note.trim()};}
export function dateLabel(e:Experience){if(!e.startDate&&!e.endDate)return e.ongoing?'持续至今':'时间未记录';return(e.startDate||'开始时间未记录')+(e.ongoing?' — 至今':e.endDate&&e.endDate!==e.startDate?' — '+e.endDate:'');}
